// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pizerpoxuqopekmbvohh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpemVycG94dXFvcGVrbWJ2b2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwOTg4MzUsImV4cCI6MjA4MjY3NDgzNX0.btGv07xrKKSaoR0bybT4tNVU8AjsfOO5jFgd5aG8VUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});